mv = 1200;
Jw = 0.01;
rw = 0.28;
v0 = 28;
vmin = 1.4;
g = 9.81;
K = 1000;
T = 0.01;
Tbmax = 2000;
eps = 2.2204e-16;
ON =1;
%% SUCHY BETON
roadType = 1;
sim('Proper');
t1 = vv.time;
vv1 = vv.signals.values;
vw1 = vw.signals.values;
dv1 = dv.signals.values;
s1 = s.signals.values;
u1 = u.signals.values;
Tb1 = Tb.signals.values;
%% MOKRY BETON
roadType = 2;
sim('Proper');
t2 = vv.time;
vv2 = vv.signals.values;
vw2 = vw.signals.values;
dv2 = dv.signals.values;
s2 = s.signals.values;
u2 = u.signals.values;
Tb2 = Tb.signals.values;
%% ŒNIEG
roadType = 3;
sim('Proper');
t3 = vv.time;
vv3 = vv.signals.values;
vw3 = vw.signals.values;
dv3 = dv.signals.values;
s3 = s.signals.values;
u3 = u.signals.values;
Tb3 = Tb.signals.values;
%% LÓD
roadType = 4;
sim('Proper');
t4 = vv.time;
vv4 = vv.signals.values;
vw4 = vw.signals.values;
dv4 = dv.signals.values;
s4 = s.signals.values;
u4 = u.signals.values;
Tb4 = Tb.signals.values;
%% WYKRESY
figure;
hold on; grid on;
plot(t1,vv1,t2,vv2,t3,vv3,t4,vv4);
title("Prêdkoœæ pojazdu");
xlabel("Czas [s]"); ylabel("Prêdkoœæ [m/s]");
legend("SUCHY BETON","MOKRY BETON","ŒNIEG","LÓD",'Location','SouthWest');
hold off;
figure;
hold on; grid on;
plot(t1,dv1,t2,dv2,t3,dv3,t4,dv4);
title("Przebyty dystans");
xlabel("Czas [s]"); ylabel("Dystans [m]");
legend("SUCHY BETON","MOKRY BETON","ŒNIEG","LÓD",'Location','NorthWest');
hold off;
figure;
hold on;grid on;
plot(t1,s1,t2,s2,t3,s3,t4,s4);
title("Poœlizg");
xlabel("Czas [s]"); ylabel("Poœlizg");
legend("SUCHY BETON","MOKRY BETON","ŒNIEG","LÓD",'Location','NorthWest');
hold off;
figure;
hold on; grid on;
plot(t1,u1,t2,u2,t3,u3,t4,u4);
title("Wspó³czynnik tarcia ");
xlabel("Czas [s]"); ylabel("Wspó³czynnik tarcia");
legend("SUCHY BETON","MOKRY BETON","ŒNIEG","LÓD");
hold off;
figure;
hold on; grid on;
plot(t1,Tb1,t2,Tb2,t3,Tb3,t4,Tb4);
title("Moment hamowania ");
xlabel("Czas [s]"); ylabel("Moment hamowania [N*m]");
legend("SUCHY BETON","MOKRY BETON","ŒNIEG","LÓD");
hold off;
figure;
hold on; grid on;
plot(t1,vw1,t2,vw2,t3,vw3,t4,vw4);
title("Prêdkoœæ ko³a");
xlabel("Czas [s]"); ylabel("Prêdkoœæ [m/s]");
legend("SUCHY BETON","MOKRY BETON","ŒNIEG","LÓD");
hold off;
